while(true) {   //L-part-sc-b
  // Avanza `l' lo mas a la derecha posible ...
  // Retrocede `r' lo mas a la izquierda posible ...
  if (l>r) break;
  // Intercambia los elementos en `l' y `r' ...
}
                //L-part-sc-e
